[FileSettings]
    FileName = "/users/php20hti/php20hti/public/chains/non_adaptive_normal_chain/Delayed_Fit_Long_Chains_no_delay_adapt_0_1.root"
    ChainName = "posteriors"
    ParameterNames = ["sin2th", "sin2th","delm2_12", "delta", "xsec"]
    LabelName = "LogL"

[FitterSettings]
    FitterObject = "GradientBoost" # "RandomForest"