[FileSettings]
    FileName = "/users/php20hti/php20hti/public/chains/all_par_chain_without_adaption.root"
    # FileName = "/users/php20hti/t2ksft/regeneration_times_project/inputs/markov_chains/oscpar_only_datafit.root"
    ChainName = "posteriors"
    # ChainName = "osc_posteriors"
    ParameterNames = ["sin2th","delm2", "delta", "xsec", "sk", "nd"]
    # ParameterNames = ["d", "th"]
    LabelName = "LogL"
    IgnoredParameters = ["LogL_systematic_xsec_cov", "Log", "LogL_systematic_nddet_cov", ]
    ParameterCuts = ["LogL<12345678", "step>10000"]
    Verbose = false
    ModelOutputName="histboost_model_full.pkl"


[FitterSettings]
    FitterPackage = "SciKit"
#    FitterName = "RandomForest"
    FitterName = "HistBoost"
    TestSize = 0.8
    # Set fitter Hyper Parameters
    [FitterSettings.FitterKwargs]
            # n_jobs = 32
            verbose=true
            max_iter = 10000
            # n_estimators = 200