[FileSettings]
    FileName = "/users/php20hti/php20hti/public/chains/non_adaptive_normal_chain/Delayed_Fit_Long_Chains_no_delay_adapt_0_1.root"
    # FileName = "/users/php20hti/t2ksft/regeneration_times_project/inputs/markov_chains/oscpar_only_datafit.root"
    ChainName = "posteriors"
    # ChainName = "osc_posteriors"
    ParameterNames = ["sin2th","delm2_12", "delta", "xsec"]
    # ParameterNames = ["d", "th"]
    LabelName = "LogL"
    IgnoredParameters = ["LogL_systematic_xsec_cov"]
    ParameterCuts = ["LogL<12345678", "step>10000"]
    Verbose = true


[FitterSettings]
    FitterPackage = "SciKit"
    FitterName = "RandomForest"
    # FitterName = "AdaBoost"
    TestSize = 0.2
    # Set fitter Hyper Parameters
    [FitterSettings.FitterKwargs]
            n_jobs = 32
            verbose=true
            # n_estimators = 200